### ISSUE TITLE
Few questions related to the Speakers of the Conference

### ISSUE THREAD

**Issue by harshbisle** [nescalas/nescala-2023-planning#14]
1. Are you willing to sign the [Speaker Engagement Agreement](https://github.com/speakers-in-tech/sea/blob/main/SEA.md)?
   2. Do you offer free tickets to speakers?
   3. Do you reimburse any of the speaker expenses? such as Travel, accommodation, food, etc. 
   4. Do you provide any compensation to the speakers for the event?

**Comment by jducoeur** [comment]
We are not playing John deGoes' silly power game -- he is attempting to passive-aggressively dictate terms to the community, and we will not be participating in that.

**Comment by harshbisle** [comment]
Please accept my apologies for troubling you with this matter.

**Comment by jducoeur** [comment]
@harshbisle Not a problem, and not your fault -- this particular bit of foolishness is only obvious to those of us who have to pay attention to John's antics.

**Comment by harshbisle** [comment]
Thank You! @jducoeur for accepting my apologies—also, All the best with organizing the conference :rocket:
